### ISSUE TITLE
Is this repo fully set up and who owns handling pull requests? 

### ISSUE THREAD

**Issue by billburnseh** [open-infrastructure-labs/operate-first-workloads#4]
Via the new operate-first.cloud, which points to the README.md here, we are exposing incorrect information (like the meeting info, which has shifted by 1/2 hour and the chat setup. I have made changes and sent pull requests. Who takes it from there?

**Comment by tumido** [comment]
This repo content will be migrated and repo closed. Thanks for raising this issue :+1:
